<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4],
             [2 5 7],
             [5 9 6]]
      B   = [[1 0 0],
             [0 1 0],
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [56]:
def matrixmultiplication(a,b):
    c=[]                          
    if(len(a[0]) == len(b)):
        #tlist=[]
        for x in range(len(a)):
            tlist=[]
            for y in range(len(b[0])):
                sum_m=0
                for z in range(len(a)):
                    sum_m +=(a[x][z]*b[z][y])        
                tlist.append(sum_m)
            c.append(tlist)    
        for alpha in c:
            print(alpha)
    else:
        print("Not Possible")

In [57]:
matrixmultiplication([[1, 2],[3, 4]],[[1,2,3,4,5],[5,6,7,8,9]])

[11, 14, 17, 20, 23]
[23, 30, 37, 44, 51]


In [58]:
matrixmultiplication([[1, 2],[3, 4]],[[1,4],[5,6],[7,8],[9,6]])

Not Possible


In [59]:
matrixmultiplication([[1,3,4],[2,5,7],[5,9,6]],[[1,0,0],[0,1,0],[0,0,1]])

[1, 3, 4]
[2, 5, 7]
[5, 9, 6]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    #.
    #.
    #.
    return #selected_random_number

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [77]:
def replace_digit(String):
    count = 0
    tlist = list(String)
    for x in range(len(tlist)):
        if(tlist[x].isnumeric()):
            count += 1
    print("#"*count)   

In [78]:
replace_digit('#2a$#b%c%561# ')

####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [29]:
def display_dash_board(students,Marks):
    stud_n =[]
    stud_m =[]
    dict1 = dict(zip(students,Marks))
    stud_am = sorted(Marks)
    stud_m = sorted(Marks,reverse = True)
    print("a.",end='\n')
    for x in range(0,5):
        for Students,Marks in dict1.items():
            if Marks == stud_m[x]:
                print(Students,":",Marks)
    print("  ")            
    print("b.",end='\n')
    for x in range(0,5):
        for Students,Marks in dict1.items():
            if Marks == stud_am[x]:
                print(Students,":",Marks)
    print("  ")            
    print("c.",end='\n')
    s = int(.25*len(stud_am))
    e = int(.75*len(stud_am))
    for x in range(s,e):
        for Students,Marks in dict1.items():
            if Marks == stud_am[x]:
                print(Students,":",Marks)              

In [30]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
display_dash_board(Students,Marks)

a.
student8 : 98
student10 : 80
student2 : 78
student5 : 48
student7 : 47
  
b.
student3 : 12
student4 : 14
student9 : 35
student6 : 43
student1 : 45
  
c.
student9 : 35
student6 : 43
student1 : 45
student7 : 47
student5 : 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [44]:
import math
def closest_points_to_p(S, P):
    dis_list = []
    sort_dis = []
    for a in range(len(S)):
        point = S[a]
        x =point[0]
        y = point[1]
        p = P[0]
        q = P[1]
        distance = math.acos(((x*p)+(y*q))/(math.sqrt((x**2)+(y**2)) * math.sqrt((p**2)+(q**2))))
        dis_list.append(distance)
    dict_1 = dict(zip(S,dis_list))
    sort_dis = sorted(dis_list)
    print("Output:",end='\n')
    for b in range(0,5):
        for S,dis_list in dict_1.items():
            if dis_list == sort_dis[b]:
                print(S)

In [45]:
S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
closest_points_to_p(S, P)

Output:
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4),(-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [194]:
import math
import re
def i_am_the_one(red,blue,line):
    print("Output:",end='\n')
    for equ in range(len(line)):
        list_red=[]
        list_blue=[]
        count = 0
        coff = re.findall(r'[\d\.\-\+]+', line[equ])
        for Red in range(len(red)):
            r_x = red[Red][0]
            r_y = red[Red][1]
            r_value = (r_x*(float(coff[0])))+(r_y*(float(coff[1])))+float(coff[2])
            list_red.append(r_value)
        for Blue in range(len(blue)):
            b_x = blue[Blue][0]
            b_y = blue[Blue][1]
            b_value = (b_x*(float(coff[0])))+(b_y*(float(coff[1])))+float(coff[2])
            list_blue.append(b_value)
        for value in range(len(list_blue)):
            if(list_red[value]>=0.0 and list_blue[value]<0.0 or list_red[value]<0.0 and list_blue[value]>=0.0):
                count += 1
        if(count == len(list_blue)):
            print('YES')
        else:
            print('NO')      

In [195]:
red= [(1,1),(2,1),(4,2),(2,4),(-1,4)]
blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
line=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
i_am_the_one(red,blue,line)

Output:
YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [322]:
def curve_smoothing(String):
    pv=[]
    nv=[]
    String = String.split(',')
    for x in range(len(String)):
        if(String[x] != '_'):
            pv.append(x)
            nv.append(String[x])
    for x in range()
    
    
    

In [323]:
S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)

[2, 6] ['30', '50']


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [571]:
def compute_conditional_probabilites(A):
    f,s,e,f_s,s_s,s_e=[],[],[],[],[],[]
    ef_list = []
    nr,dr = 0,0
    
    for x in range(len(A)):
        ele,ele_s,ele_f = 0,0,0        
        for y in range(len(A)):            
            if(A[x]==A[y]):
                ele += 1                                                
            if(A[x][0] == A[y][0]):
                ele_f += 1            
                f.append(A[x][0])                
            if(A[x][1] == A[y][1]):
                ele_s += 1               
                s.append(A[x][1])
        e.append(str(ele))        
        f_s.append(str(ele_f))  
        s_s.append(str(ele_s))        
    f = list(set(f))
    s = list(set(s)) 
    print("f:",f)
    print("s:",s)
    print("A:",A)
    print("e:",e)
    print("f_s:",f_s)
    print("s_s:",s_s)
    print("     ")
    print("//\\----------------------------------------------------------------------------//\\")
    print(" ")
    
    for x in range(len(s)):
        xcount = 0    
        for y in range(len(A)):
            if(s[x] == A[y][1]):
                xcount +=1  
        print(s[x],xcount)
        
d_s = dict(zip(s,str(xcount)))
print(d_s)

     
 
    for x in range(len(f)):
        ele_l=[]
        ele_l.append(f[x])
        for y in range(len(s)):
            ele_l.append(s[y])
            for z in range(len(A)):
                if(ele_l == A[z]):
                    print(ele_l)
                    nr = e[z]
                    dr = s_s[z]  
                    print(nr,"/",dr)
                elif(ele_l != A[z]):
                    nr = 0
#                     dr = 
                    
            ele_l.pop()
        


    

                

IndentationError: unexpected indent (<ipython-input-571-22d637073499>, line 44)

In [572]:
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)

f: ['F1', 'F3', 'F2', 'F5', 'F4']
s: ['S3', 'S2', 'S1']
A: [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'], ['F4', 'S3'], ['F5', 'S1']]
e: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1']
f_s: ['2', '3', '2', '2', '3', '2', '3', '2', '2', '1']
s_s: ['4', '3', '3', '3', '3', '3', '4', '4', '3', '4']
     
//\----------------------------------------------------------------------------//\
 
S3 3
{'S3': '3'}
S2 3
{'S3': '3'}
S1 4
{'S3': '4'}
['F1', 'S2']
1 / 3
['F1', 'S1']
1 / 4
['F3', 'S3']
1 / 3
['F3', 'S2']
1 / 3
['F2', 'S3']
1 / 3
['F2', 'S2']
1 / 3
['F2', 'S1']
1 / 4
['F5', 'S1']
1 / 4
['F4', 'S3']
1 / 3
['F4', 'S1']
1 / 4


In [ ]:
 P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3

<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [25]:
def string_features(s1,s2):
    s3 = []
    s1 = s1.split()
    s2 = s2.split()
    s3 = s1+s2
    print("a.",len(set(s1).intersection(set(s2))))
    print("b.",list(set(s3)-set(s2)))
    print("c.",list(set(s3)-set(s1)))

In [26]:
string_features("the first column F will contain only 5 uniques values","the second column S will contain only 3 uniques values")

a. 7
b. ['F', 'first', '5']
c. ['second', '3', 'S']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [19]:
import math
def compute_log_loss(A):
    pro = 0
    for x in range(len(A)):
        pro += -1*A[x][0]*math.log10(A[x][1])                            
    print(pro/len(A))

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
compute_log_loss(A)

0.19257593903009612
